services:
  api:
    image: ghcr.io/ferrarilucas/interpix-api:latest
    container_name: pix-inter-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_OPTIONS=--max-old-space-size=1024
    volumes:
      - ./certs:/usr/src/app/certs 